import { ThemeId } from './types';

export interface ThemePreset {
  id: ThemeId;
  nameBn: string;
  nameEn: string;
  badge: string;
  description: string;
  previewColors: string[];
  bgClass: string;
  cardBgClass: string;
  headerBgClass: string;
  navBgClass: string;
  primaryAccentClass: string;
  accentBtnClass: string;
  accentTextClass: string;
  cardHoverClass: string;
  badgeClass: string;
  modalBgClass: string;
  inputBgClass: string;
  isLight: boolean;
}

export const THEMES: Record<ThemeId, ThemePreset> = {
  emerald_pro: {
    id: 'emerald_pro',
    nameBn: 'এমারেল্ড প্রু (Emerald Cyber Dark)',
    nameEn: 'Emerald Pro Dark',
    badge: '🟢 Emerald Pro',
    description: 'আধুনিক ডার্ক থিম উইথ সাইবার গ্রীন ও রয়্যাল নেভি একসেন্ট',
    previewColors: ['#020617', '#0f172a', '#10b981'],
    bgClass: 'bg-slate-950 text-slate-100',
    cardBgClass: 'bg-slate-900/90 border border-slate-800 text-slate-100',
    headerBgClass: 'bg-slate-900/90 border-b border-slate-800 text-slate-100 backdrop-blur-md',
    navBgClass: 'bg-slate-900/95 border-t border-slate-800 text-slate-100 backdrop-blur-lg',
    primaryAccentClass: 'bg-emerald-500 text-slate-950',
    accentBtnClass: 'bg-emerald-500 hover:bg-emerald-400 text-slate-950 shadow-lg shadow-emerald-500/20 font-bold',
    accentTextClass: 'text-emerald-400',
    cardHoverClass: 'hover:border-emerald-500/50',
    badgeClass: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20',
    modalBgClass: 'bg-slate-900 border border-slate-800 text-slate-100',
    inputBgClass: 'bg-slate-950 border-slate-800 text-slate-100 focus:border-emerald-500',
    isLight: false,
  },
  gold_luxury: {
    id: 'gold_luxury',
    nameBn: 'গোল্ড লাক্সারি (Royal Gold & Obsidian)',
    nameEn: 'Gold Luxury Obsidian',
    badge: '🏆 Gold Luxury',
    description: 'রাজকীয় প্রিমিয়াম ডার্ক গোল্ড ও ব্ল্যাক ভিআইপি ব্যাংকিং নান্দনিকতা',
    previewColors: ['#09090b', '#18181b', '#f59e0b'],
    bgClass: 'bg-zinc-950 text-amber-50',
    cardBgClass: 'bg-zinc-900/90 border border-amber-900/40 text-amber-50',
    headerBgClass: 'bg-zinc-900/95 border-b border-amber-900/50 text-amber-50 backdrop-blur-md',
    navBgClass: 'bg-zinc-900/95 border-t border-amber-900/50 text-amber-50 backdrop-blur-lg',
    primaryAccentClass: 'bg-amber-500 text-slate-950',
    accentBtnClass: 'bg-amber-500 hover:bg-amber-400 text-slate-950 shadow-lg shadow-amber-500/20 font-bold',
    accentTextClass: 'text-amber-400',
    cardHoverClass: 'hover:border-amber-500/50',
    badgeClass: 'bg-amber-500/10 text-amber-300 border border-amber-500/20',
    modalBgClass: 'bg-zinc-900 border border-amber-800/40 text-amber-50',
    inputBgClass: 'bg-zinc-950 border-amber-900/50 text-amber-100 focus:border-amber-500',
    isLight: false,
  },
  midnight_cyber: {
    id: 'midnight_cyber',
    nameBn: 'মিডনাইট সাইবার (Neon Purple & Cyan)',
    nameEn: 'Midnight Cyber Synth',
    badge: '⚡ Midnight Cyber',
    description: 'ফিউচারিস্টিক সাইবারনেটিক পার্পল ও নিয়ন সায়ান গেমিং লুক',
    previewColors: ['#0a0a0a', '#2e1065', '#06b6d4'],
    bgClass: 'bg-neutral-950 text-cyan-50',
    cardBgClass: 'bg-purple-950/40 border border-purple-800/40 text-cyan-50',
    headerBgClass: 'bg-purple-950/80 border-b border-purple-800/50 text-cyan-50 backdrop-blur-md',
    navBgClass: 'bg-purple-950/90 border-t border-purple-800/50 text-cyan-50 backdrop-blur-lg',
    primaryAccentClass: 'bg-cyan-500 text-slate-950',
    accentBtnClass: 'bg-cyan-500 hover:bg-cyan-400 text-slate-950 shadow-lg shadow-cyan-500/20 font-bold',
    accentTextClass: 'text-cyan-400',
    cardHoverClass: 'hover:border-cyan-500/50',
    badgeClass: 'bg-cyan-500/10 text-cyan-300 border border-cyan-500/20',
    modalBgClass: 'bg-purple-950/90 border border-cyan-500/30 text-cyan-50',
    inputBgClass: 'bg-neutral-950 border-cyan-800/50 text-cyan-100 focus:border-cyan-400',
    isLight: false,
  },
  clean_light: {
    id: 'clean_light',
    nameBn: 'ক্লিন লাইট (Minimalist Studio White)',
    nameEn: 'Clean Light Studio',
    badge: '☀️ Clean Light',
    description: 'উজ্জ্বল, ক্লিন, হাই-কনট্রাস্ট প্রফেশনাল হোয়াইট ইন্টারফেস',
    previewColors: ['#f1f5f9', '#ffffff', '#0d9488'],
    bgClass: 'bg-slate-100 text-slate-900',
    cardBgClass: 'bg-white border border-slate-200 text-slate-900 shadow-sm',
    headerBgClass: 'bg-white/95 border-b border-slate-200 text-slate-900 shadow-sm backdrop-blur-md',
    navBgClass: 'bg-white/95 border-t border-slate-200 text-slate-900 shadow-sm backdrop-blur-lg',
    primaryAccentClass: 'bg-teal-600 text-white',
    accentBtnClass: 'bg-teal-600 hover:bg-teal-500 text-white shadow-lg shadow-teal-600/20 font-bold',
    accentTextClass: 'text-teal-600',
    cardHoverClass: 'hover:border-teal-500/50',
    badgeClass: 'bg-teal-50 text-teal-800 border border-teal-200',
    modalBgClass: 'bg-white border border-slate-200 text-slate-900 shadow-2xl',
    inputBgClass: 'bg-slate-50 border-slate-300 text-slate-900 focus:border-teal-600',
    isLight: true,
  },
  royal_sapphire: {
    id: 'royal_sapphire',
    nameBn: 'রয়্যাল স্যাফায়ার (Ocean Sapphire Blue)',
    nameEn: 'Royal Sapphire Ocean',
    badge: '💎 Royal Sapphire',
    description: 'গভীর রয়্যাল ওশান ব্লু কর্পোরেট ব্যাংকিং প্রিমিয়াম লুক',
    previewColors: ['#082f49', '#0c4a6e', '#38bdf8'],
    bgClass: 'bg-blue-950 text-sky-50',
    cardBgClass: 'bg-blue-900/50 border border-blue-800/50 text-sky-50',
    headerBgClass: 'bg-blue-900/90 border-b border-blue-800/70 text-sky-50 backdrop-blur-md',
    navBgClass: 'bg-blue-900/95 border-t border-blue-800/70 text-sky-50 backdrop-blur-lg',
    primaryAccentClass: 'bg-sky-400 text-slate-950',
    accentBtnClass: 'bg-sky-400 hover:bg-sky-300 text-slate-950 shadow-lg shadow-sky-400/20 font-bold',
    accentTextClass: 'text-sky-400',
    cardHoverClass: 'hover:border-sky-400/50',
    badgeClass: 'bg-sky-500/10 text-sky-300 border border-sky-500/20',
    modalBgClass: 'bg-blue-950 border border-sky-500/30 text-sky-50',
    inputBgClass: 'bg-blue-950 border-sky-800/50 text-sky-100 focus:border-sky-400',
    isLight: false,
  },
  crimson_ruby: {
    id: 'crimson_ruby',
    nameBn: 'ক্রিমসন রুবি (Crimson Ruby Velvet)',
    nameEn: 'Crimson Ruby Velvet',
    badge: '🌹 Crimson Ruby',
    description: 'আভিজাত্যপূর্ণ রুবি রেড ও ডিপ ভেলভেট রয়্যাল ডার্ক মোড',
    previewColors: ['#450a0a', '#7f1d1d', '#f43f5e'],
    bgClass: 'bg-stone-950 text-rose-50',
    cardBgClass: 'bg-rose-950/30 border border-rose-900/40 text-rose-50',
    headerBgClass: 'bg-rose-950/80 border-b border-rose-900/50 text-rose-50 backdrop-blur-md',
    navBgClass: 'bg-rose-950/90 border-t border-rose-900/50 text-rose-50 backdrop-blur-lg',
    primaryAccentClass: 'bg-rose-500 text-white',
    accentBtnClass: 'bg-rose-600 hover:bg-rose-500 text-white shadow-lg shadow-rose-600/25 font-bold',
    accentTextClass: 'text-rose-400',
    cardHoverClass: 'hover:border-rose-500/50',
    badgeClass: 'bg-rose-500/10 text-rose-300 border border-rose-500/20',
    modalBgClass: 'bg-stone-950 border border-rose-800/40 text-rose-50',
    inputBgClass: 'bg-stone-950 border-rose-900/50 text-rose-100 focus:border-rose-500',
    isLight: false,
  },
  sunset_amber: {
    id: 'sunset_amber',
    nameBn: 'সানসেট অরেঞ্জ (Warm Sunset Amber)',
    nameEn: 'Warm Sunset Amber',
    badge: '🌅 Sunset Amber',
    description: 'উষ্ণ সূর্যাস্তের অরেঞ্জ, ব্রাউন ও ওয়ার্ম অ্যাম্বার প্রাইভেট ব্যাংকিং লুক',
    previewColors: ['#1c1917', '#451a03', '#f97316'],
    bgClass: 'bg-stone-950 text-orange-50',
    cardBgClass: 'bg-amber-950/30 border border-orange-900/40 text-orange-50',
    headerBgClass: 'bg-amber-950/80 border-b border-orange-900/50 text-orange-50 backdrop-blur-md',
    navBgClass: 'bg-amber-950/90 border-t border-orange-900/50 text-orange-50 backdrop-blur-lg',
    primaryAccentClass: 'bg-orange-500 text-slate-950',
    accentBtnClass: 'bg-orange-500 hover:bg-orange-400 text-slate-950 shadow-lg shadow-orange-500/25 font-bold',
    accentTextClass: 'text-orange-400',
    cardHoverClass: 'hover:border-orange-500/50',
    badgeClass: 'bg-orange-500/10 text-orange-300 border border-orange-500/20',
    modalBgClass: 'bg-stone-950 border border-orange-800/40 text-orange-50',
    inputBgClass: 'bg-stone-950 border-orange-900/50 text-orange-100 focus:border-orange-500',
    isLight: false,
  },
  amethyst_purple: {
    id: 'amethyst_purple',
    nameBn: 'অ্যামেথিস্ট ভায়োলেট (Royal Amethyst Glass)',
    nameEn: 'Amethyst Violet Glass',
    badge: '🔮 Amethyst Violet',
    description: 'রাজকীয় ভায়োলেট ও গভীর পার্পল আর্ট লাক্সারি ব্যাংকিং লুক',
    previewColors: ['#1e1b4b', '#312e81', '#a855f7'],
    bgClass: 'bg-slate-950 text-purple-50',
    cardBgClass: 'bg-purple-900/30 border border-purple-800/40 text-purple-50',
    headerBgClass: 'bg-purple-950/80 border-b border-purple-800/50 text-purple-50 backdrop-blur-md',
    navBgClass: 'bg-purple-950/90 border-t border-purple-800/50 text-purple-50 backdrop-blur-lg',
    primaryAccentClass: 'bg-purple-500 text-white',
    accentBtnClass: 'bg-purple-600 hover:bg-purple-500 text-white shadow-lg shadow-purple-600/25 font-bold',
    accentTextClass: 'text-purple-400',
    cardHoverClass: 'hover:border-purple-500/50',
    badgeClass: 'bg-purple-500/10 text-purple-300 border border-purple-500/20',
    modalBgClass: 'bg-slate-950 border border-purple-800/40 text-purple-50',
    inputBgClass: 'bg-slate-950 border-purple-900/50 text-purple-100 focus:border-purple-500',
    isLight: false,
  },
  nordic_frost: {
    id: 'nordic_frost',
    nameBn: 'নর্ডিক ফ্রস্ট (Nordic Ice Cyan Light)',
    nameEn: 'Nordic Ice Cyan Light',
    badge: '❄️ Nordic Frost',
    description: 'শীতল সায়ান ও সফট ফ্রস্টেড আইস হোয়াইট মডার্ন ক্লিন থিম',
    previewColors: ['#ecfeff', '#cffaff', '#0891b2'],
    bgClass: 'bg-cyan-50 text-slate-900',
    cardBgClass: 'bg-white/90 border border-cyan-200 text-slate-900 shadow-sm backdrop-blur-sm',
    headerBgClass: 'bg-white/90 border-b border-cyan-200 text-slate-900 shadow-sm backdrop-blur-md',
    navBgClass: 'bg-white/95 border-t border-cyan-200 text-slate-900 shadow-sm backdrop-blur-lg',
    primaryAccentClass: 'bg-cyan-600 text-white',
    accentBtnClass: 'bg-cyan-600 hover:bg-cyan-500 text-white shadow-lg shadow-cyan-600/20 font-bold',
    accentTextClass: 'text-cyan-600',
    cardHoverClass: 'hover:border-cyan-500/50',
    badgeClass: 'bg-cyan-100 text-cyan-800 border border-cyan-300',
    modalBgClass: 'bg-white border border-cyan-200 text-slate-900 shadow-2xl',
    inputBgClass: 'bg-cyan-50/50 border-cyan-300 text-slate-900 focus:border-cyan-600',
    isLight: true,
  },
  emerald_mint_light: {
    id: 'emerald_mint_light',
    nameBn: 'মিন্ট স্টুডিও (Fresh Mint Light)',
    nameEn: 'Fresh Mint Light Studio',
    badge: '🌿 Mint Studio',
    description: 'তাজা পেপার হোয়াইট ও অর্গানিক ফ্রেশ সফট মিন্ট গ্রিন থিম',
    previewColors: ['#f0fdf4', '#dcfce7', '#16a34a'],
    bgClass: 'bg-emerald-50/60 text-slate-900',
    cardBgClass: 'bg-white border border-emerald-200 text-slate-900 shadow-sm',
    headerBgClass: 'bg-white/90 border-b border-emerald-200 text-slate-900 shadow-sm backdrop-blur-md',
    navBgClass: 'bg-white/95 border-t border-emerald-200 text-slate-900 shadow-sm backdrop-blur-lg',
    primaryAccentClass: 'bg-emerald-600 text-white',
    accentBtnClass: 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg shadow-emerald-600/20 font-bold',
    accentTextClass: 'text-emerald-600',
    cardHoverClass: 'hover:border-emerald-500/50',
    badgeClass: 'bg-emerald-100 text-emerald-800 border border-emerald-300',
    modalBgClass: 'bg-white border border-emerald-200 text-slate-900 shadow-2xl',
    inputBgClass: 'bg-emerald-50/50 border-emerald-300 text-slate-900 focus:border-emerald-600',
    isLight: true,
  },
};

export const getTheme = (id?: string): ThemePreset => {
  if (id && id in THEMES) {
    return THEMES[id as ThemeId];
  }
  return THEMES.emerald_pro;
};

